Traceback (most recent call last):
  File "c:\Users\Даниил\Desktop\Диплом\rrl-server\src\python-scripts\add_training.py", line 12, in <module>
    ulid = sys.argv[2]
           ~~~~~~~~^^^
IndexError: list index out of range
